### PR TITLE
Here is the red where is the red, hungarian lucky game :)

### PR DESCRIPTION
**Pull request by pilou**
Couldn't  fix your red with rexexp because i lost the separator, even when i tried positive lookahead.

Also string regex didn't work, only the `new RegExp` can you tell me why?
Didn't split: `expression.split('/[\+]/');`
Did split: `expression.split(new RegExp('[\+]'));`

### CODE REVIEW

**Comment by Wilzi** [comment]
Here is your answer :)
tl;dr regexp inside apostrophes compiled as a string not an expression
https://jsbin.com/koqojo/3/edit?js,console

**Comment by Wilzi** [comment]
lodash is unused depenceny, please remove it and run 'npm t' before commit (check eslint)
I'll create a pre-commit hook for eslint

Thanks

**Comment by pilou** [comment]
Man, I added the apostrophes, it was focus blindness. :)

Ok, I'll remove the lodash, I was using _.escapeRegExp.

I'll also do the lint prehook.

XOXO :)

**Comment by pilou** [comment]
Please reconsider accepting the pull request.
How bow dah?

**Comment by Wilzi** [comment]
LGTM :)

**Pull request merged**
